#+TITLE: sculpt

Sculpting shapes and sounds with gestures using LeapMotion.
Residency project of Konstantinos Vasilakos.

Includes:
- SuperCollider classes and workspace files.
- ChucK code files.
- Config files for LeapMotion.
- Design and help doc.

** Hardware

- ca 5 contact piezos, connected to any surface of objects, big or small
  - Note: the piezos should be soldered to common audio (mike) cable leading to Arduino (soldering/breadboard) or sound card (TS 0.5" input jack).
- 1 Arduino board for triggering from piezos
- 1 Sound card for audio input from piezos, and for sound output.

- Laptops / macmini

** Software

*** SuperCollider

Download SuperCollider from: http://supercollider.sourceforge.net/downloads/
*** SuperCollider Libraries:
  - Utopia (https://github.com/muellmusik/Utopia)
  - tiny-sc (https://github.com/iani/tiny-sc)
  - sculpt (This library: https://github.com/eastn/sculpt, folder: Classes)
*** ChucK

Download ChucK from: http://chuck.cs.princeton.edu/release/

ChucK code is found in this library inside folder: ChucK.

*** LeapMotion Configuration Files

Files for configuring LeapMotion so as to send OSC to SuperCollider using the application Geco are located in the present library inside folder: LeapMotionSetup.

*** ChucK - SuperCollider Code

Some coding snippets to test OSC communication between ChucK & SuperCollider. Downloaded from:http://www.ixi-software.net/workshops/files.php
